app/users/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, HiddenField, PasswordField, SubmitField, RadioField
from wtforms.validators import DataRequired

class NewUserFrom(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    password1 = PasswordField('password1', validators=[DataRequired()])
    password2 = PasswordField('password2', validators=[DataRequired()])

class UpdateUserForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    password1 = PasswordField('password1')
    password2 = PasswordField('password2')
    id = HiddenField('id')

app/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__, url_prefix='/users')

from . import views

app/users/views.py
from flask import request, render_template, url_for, g, flash, redirect, session, jsonify
from werkzeug.security import generate_password_hash

from app import db
from .forms import UpdateUserForm, NewUserFrom
from app.models import Users, DateNow

from . import users

@users.route('/newUser', methods=['GET','POST'])
def new_user():
    newUserForm = NewUserFrom()
    context = {
        'newUserForm': newUserForm
    }
    if request.method == 'POST':
        #app.config['TESTING'] lo hice para que no me tronaran las pruebas unitarias
        #mientras encuentro la forma de evadir la session
        if newUserForm.validate_on_submit:
            username = request.form["username"]
            existent_user = Users.query.filter_by(username_user=username).first()
            if request.form['password1'] != request.form['password2']:
                flash('Passwords do not match', 'warning')
                #Redireccionando no pude mandar los codigos http solo me funcionó de esta manera
                #redirect solo acepta codigos 301-308, si no te pone una pagina fea
                #No esta mal pero yo quería usar redirect 
                return render_template('new_user.html', **context), 401
            if existent_user is None:
                #hash the password
                hashed_pw = generate_password_hash(request.form["password1"], method="sha256")
                #create a new user from clas User
                new_user = Users(username_user=username, 
                                        role_user=request.form['role'],
                                        created_date_user=DateNow(True), password_user=hashed_pw)
                #save the user in the database
                db.session.add(new_user)
                db.session.commit()
                flash("The user has beeen registered successfully.", 'success')
                return redirect(url_for('users.render_users'))
            else:
                flash("The user already exists.", 'danger')
                return redirect(url_for('users.new_user'), code=303)
        else:
            #Mejorar esto, pero ya no tengo tiempo
            return "nop"
    elif request.method == 'GET':
        return render_template('new_user.html', **context)
    else:
        return "Method not allowed"

@users.route('/updateUser', methods=['POST', 'PUT'])
def update_user(): 
    updateUserForm = UpdateUserForm()  
    if updateUserForm.validate_on_submit:
        existent_user = Users.query.filter_by(username_user=request.form["username"]).first()
        #IF the user founded and the id received are diffrents, means that is other user and exists
        if existent_user and ( str(existent_user.id_user) != str(request.form["id"]) ):
            flash("The user already exists.", 'danger')
            return redirect(url_for('users.edit_user', idUser=request.form["id"]), code=303 )
        else:
            if request.form['password1'] != request.form['password2']:
                flash('Passwords do not match', 'warning')
                return redirect(url_for('users.edit_user', idUser=request.form["id"]) )
            #Get the user from the database
            updating_user = Users.query.filter_by(id_user=request.form["id"]).first()
            if request.form['password1'] != '':
                #hash the password
                hashed_pw = generate_password_hash(request.form["password1"], method="sha256")
                updating_user.password_user = hashed_pw
            updating_user.username_user = request.form['username']
            updating_user.role_user = request.form['role']
            updating_user.updated_date_user = DateNow(True)
            #save the user in the database
            db.session.add(updating_user)
            db.session.commit()
            flash("The user has beeen updated successfully.", 'success')
            return redirect(url_for('users.render_users'))
    else:
        #Mejorar esto, pero ya no tengo tiempo
        return "nop"

@users.route('/editUser/<int:idUser>')
def edit_user(idUser):
    updateUserForm = UpdateUserForm()
    values=Users.query.filter_by(id_user=idUser).first()
    context = {
        'values': values,
        'updateUserForm': updateUserForm
    }
    return render_template('update_user.html', **context)

#DELETE USER
@users.route('/deleteUser/<int:id>', methods=["DELETE"])
def delete_user(id):
    deleting_user = Users.query.filter_by(id_user=id).first()
    if delete_user is None:  
        return "The user was not found.", 400    
    db.session.delete(deleting_user)
    db.session.commit()
    return jsonify("The user has been deleted successfully!."), 200

@users.route('/users')
def render_users():
    users = Users.query.all()
    return render_template('users.html', usersList=users)

app/templates/about.html
{% extends 'base.html' %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" type=text/css href="{{ url_for('static', filename='css/about.css') }}">
    <title>Users</title>
{% endblock %}

{% block content %}
    <h2>Motor Control Application V1.2 - 2019</h2>
    <div class="form-box" id="myModalDeleter">
            <p id="title" class="title">This is a didactic application is control a 
                motor connected to a computer and audit 
                <strong>who, what and when</strong> the motor is operated</p>
            <br/>
            <p id="title2" class="title">The goal of this application is to 
                learn all about good practice of the cycle of software development</p>
            <br/>
            <p class="title">Credits by</p>
            <br/>
            <p class="titleBorder"><strong>Professor: </strong>Ivan Rogelio Chenoweth</p>
            <br/>
            <p class="titleBorder"><strong>Student: </strong>Julio César Felix</p>

    </div>

{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <link rel="stylesheet" type=text/css href="{{ url_for('static', filename='css/baseStyles.css') }}">
    <link rel="stylesheet" type=text/css href="{{ url_for('static', filename='css/navigationBar.css') }}">
    <title>Document</title>
{% endblock %}

{% block body %}
    
    {% block navbar %}
        {% include 'navigationBar.html' %}
    {% endblock %}
    {% block content %}{% endblock %}
    {% block scripts %}
        {{ super() }}
    {% endblock %}
{% endblock %}
</body>
</html>

app/templates/delete_modal.html
<div class="form-box animated bonceInDown">
    <h1 class="title">Are you shure about delete the user test</h1>
</div>

app/templates/login.html
{% extends 'base.html' %}
{% block navbar %}        
    <link rel="stylesheet" type=text/css href="{{ url_for('static', filename='css/login.css') }}">
    <title>Login</title>
{% endblock %}     
{% block content %}
  <div class="login-body" id="login">
      <div class="form-box {{ error }}">
        <div class="form-box-header">
          <h1 class="header-login">Iniciar Sesión</h1>
        </div>
        <div class="form-box-body">
          <!-- <form id="loginForm"> -->
          <form action="{{ url_for('auth.login') }}" method='POST'>
              <div class="form-group">
                <label>Usuario</label>
                <div class="input-group margin-bottom-sm">
                  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                  {{ login_form.username(class_='form-control', placeholder='Usuario') }}
                </div>
              </div>
              <div class="form-group">
                <label>Contraseña</label> 
                <div class="input-group margin-bottom-sm">
                  <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                  {{ login_form.password(class_='form-control', placeholder='Contraseña') }} 
                </div>
              </div>
              <div class="form-group">
                <label><input id="rememberMe" type="checkbox"/> Remember me</label>
              </div>
              <div  class="btn-login-container" id="login-btn">
                {{ login_form.submit(class_='btn-login') }}
              </div>
          </form>
        </div>
      </div>
  </div>
  {% block scripts %} 
  {% endblock %}
{% endblock %}
  

app/templates/logs.html
{% extends 'base.html' %}

{% block head %}
    {{ super() }}
    <title>Users</title>
{% endblock %}

{% block content %}
    <div class="container">
    <div>
        <h1>Logs</h1>
    </div>
    <table class="table table-bordered thead-dark">
        <thead class="">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">User name</th>
                <th scope="col">Action</th>
                <th scope="col">Created Date Time</th>
            </tr>
        </thead>
        <tbody>
            {% for log, user in logslist %}
            <tr>
                <th style="vertical-align: middle;" scope="row">{{ log.id_log }}</th>
                <td style="vertical-align: middle;">{{ user.username_user }}</td>
                <td style="vertical-align: middle;">{{ log.action }}</td>
                <td style="vertical-align: middle;">{{ log.created_date_log }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

app/templates/navigationBar.html
<div style="margin: 0 5px;">
        <nav class="navigationBar">
            <ul class="nav-header">
                <li>
                    <a href="{{ url_for('users.render_users') }}"><p >Administrator</p></a>
                </li>
            </ul>
            <div class="nav-links">
                <ul class="nav-left-side">
                    <li><a href="{{ url_for('users.render_users') }}"><p class="link">Users</p></a></li>
                    <li><a href="{{ url_for('process.render_logs') }}"><p class="link">Logs</p></a></li>
                    <li><a href="{{ url_for('process.about') }}"><p class="link">About</p></a></li>
                </ul>
                <ul class="nav-right-side">
                    <li><a href="#"><p class="link">{{ g.username }}</p></a></li>
                    <li><a href="{{ url_for('auth.logout') }}"><p class="link">Logout</p></a></li>
                </ul>
            </div>
        </nav>
</div>

app/templates/new_user.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block navbar %}   
     {{ super() }}     
    <link rel="stylesheet" type=text/css href="{{ url_for('static', filename='css/new_user.css') }}">
    <title>New User</title>
{% endblock %}  
{% block content %}
    <div class="container">
        {% for category, message in get_flashed_messages(with_categories=true) %}
            <div class="alert alert-{{ category }} alert dismisible">
                <button type="button" 
                        data-dismiss="alert"
                        class="close">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
        <form class="form-box" method="POST" action="{{ url_for('users.new_user') }}">
            <h1 class="header-new-user">New User</h1>
            <br/>
            {{ newUserForm.csrf_token }}
            <div class="form-group">
                <label for="name">Username *</label>
                {{ newUserForm.username(class_='form-control') }}
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password *</label>
                {{ newUserForm.password1(class_='form-control') }}
            </div>
            <div class="form-group">
                    <label for="exampleInputPassword1">Password (again)*</label>
                    {{ newUserForm.password2(class_='form-control') }}
            </div>
            <div class="form-group">
                    <label style="margin-right: 15px;" for="customRadio1">Role: *</label>
                    <input type="radio" id="customRadio1" checked name="role" value='Administrator' class="custom-control-input">
                    <label style="margin-right: 10px;" for="customRadio1">Admin</label>
                    <input type="radio" id="customRadio2" name="role" value='User' class="custom-control-input">
                    <label class="custom-control-label" for="customRadio2">User</label>
            </div>   
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{{ url_for('users.render_users') }}" class="btn btn-default">Cancel</a>
            </div >
        </form>
    </div>

{% endblock %}

app/templates/process.html
{% extends 'base.html' %}
{% block navbar %}   
    <link rel="stylesheet" type=text/css href="{{ url_for('static', filename='css/process.css') }}">
    <title>Process</title>
{% endblock %}     
{% block content %}
<div class="process-container">
        <input id="idUser" type="hidden" value="{{ g.id_user }}"/>
        <div class="logout-box">
            <p class="logout-box-text">{{ g.username }}</p>
            <a class="logout-box-text"href="{{ url_for('auth.login') }}">Logout</a>
        </div>
        <div class="title-proces">
            <h1>Process</h1>
        </div>
        <div id="formBox" class="form-box animated">
            <p id="date">22-Agosto-2019 <strong id="hour" class="hour"></strong></p>
            <div class="btn-groups-1">
                <input id="on" class="btn-process btn btn-success" type="button" value="Power On">
                <input id="off" class="btn-process btn btn-danger" type="button" value="Power Off">
            </div>
            <div class="btn-groups-1">
                <input id="turn lef" class="btn-process btn btn-success" type="button" value="turn left">
                <input id="turn right" class="btn-process btn btn-success" type="button" value="turn right">
            </div>
        </div>
</div>
<script src="{{ url_for('static', filename='js/libraries/moment.js') }}"></script>
<script src="{{ url_for('static', filename='js/process.js') }}"></script>


{% endblock %}
  

app/templates/update_user.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block navbar %}   
     {{ super() }}     
    <link rel="stylesheet" type=text/css href="{{ url_for('static', filename='css/new_user.css') }}">
    <title>Edit User</title>
{% endblock %}  
{% block content %}
    <div class="container">
        {% for category, message in get_flashed_messages(with_categories=true) %}
            <div class="alert alert-{{ category }} alert dismisible">
                <button type="button" 
                        data-dismiss="alert"
                        class="close">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
        <form class="form-box" method="POST" action="{{ url_for('users.update_user') }}">
            <h1 class="header-new-user">Edit User</h1>
            <br/>
            {{ updateUserForm.csrf_token }}
            <div class="form-group">
                <label for="name">Username *</label>
                {{ updateUserForm.username(class_='form-control', value=values.username_user  ) }}
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                {{ updateUserForm.password1(class_='form-control') }}
            </div>
            <div class="form-group">
                    <label for="exampleInputPassword1">Password (again)</label>
                    {{ updateUserForm.password2(class_='form-control') }}
            </div>
            <div class="form-group">
                    <label style="margin-right: 15px;" for="customRadio1">Role: *</label>
                    <input type="radio" id="customRadio1" checked name="role" value='Administrator' class="custom-control-input">
                    <label style="margin-right: 10px;" for="customRadio1">Admin</label>
                    <input type="radio" id="customRadio2" name="role" value='User' class="custom-control-input">
                    <label class="custom-control-label" for="customRadio2">User</label>
            </div>  
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{{ url_for('users.render_users') }}" class="btn btn-default">Cancel</a>
            </div >
            {{ updateUserForm.id(value=values.id_user) }} 
        </form>
    </div>

{% endblock %}

app/templates/users.html
{% extends 'base.html' %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" type=text/css href="{{ url_for('static', filename='css/modal.css') }}">
    <title>Users</title>
{% endblock %}

{% block content %}
    <div class="form-box animated bounceInDown" id="myModalDeleter">
            <p id="title" class="title">Are you shure about delete the Administrator: </p>
            <p id="title2" class="nameUser">"TEST" ?</p>
            <div style="display: flex; flex-direction: row; justify-content: center; margin-top: 40px;">
                    <input id="aceptDeleteUser" style="margin-right: 15px;" class="btn btn-danger" value="Acept">
                    <input class="btn btn-default" value="Cancel" onclick="closeModal()">
            </div>
            <input id='idField' type="hidden"/>
    </div>
    <div class="container">
    {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="alert alert-{{ category }} alert dismisible">
            <button type="button" 
                    data-dismiss="alert"
                    class="close">&times;</button>
            {{ message }}
        </div>
    {% endfor %}
    <div class="space-between">
        <h1>Users</h1>
        <a class="btn btn-success" href="{{ url_for('users.new_user') }}">New user</a>
    </div>
    <table class="table  table-bordered thead-dark">
        <thead class="">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">User name</th>
                <th scope="col">Password</th>
                <th scope="col">Role</th>
                <th scope="col">Created Date</th>
                <th scope="col">Updated Date</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for user in usersList %}
            <tr>
                <th style="vertical-align: middle;" scope="row">{{ user.id_user }}</th>
                <td id="{{ user.id_user }}username"style="vertical-align: middle;">{{ user.username_user }}</td>
                <td style="vertical-align: middle;">XXX</td>
                <td id="{{ user.id_user }}role" style="vertical-align: middle;">{{ user.role_user }}</td>
                <td style="vertical-align: middle;">{{ user.created_date_user }}</td>
                {% if user.updated_date_user %}
                    <td style="vertical-align: middle;">{{ user.updated_date_user }}</td>
                {% else %}
                    <td style="vertical-align: middle;">{{ user.created_date_user }}</td>
                {% endif %}
                <td style="vertical-align: middle;">
                    <a href="{{ url_for('users.edit_user', idUser=user.id_user) }}" class="btn btn-primary">Edit</a>
                    <button onclick="openModal('{{ user.id_user }}')" class="btn btn-danger">Delete</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<script src="{{ url_for('static', filename='js/modal.js') }}"></script>

{% endblock %}